name: Feature Request
description: Suggest an idea for Monify
labels: ["enhancement"]
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
      description: Is your feature request related to a problem? Please describe.
      placeholder: I would like to see...
    validations:
      required: true
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: What should happen?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any other ways this could be solved?
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Screenshots, drawings, or anything else.
